server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:123456@${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eurka-server
